import { writable } from 'svelte/store';

const beings = writable([
  // White (Can be found in picture wins)
  {
    id: 'chapter4-being-1a',
    imgUrl: '/decks/chapter4/beings/white/bow.png',
    title:'Why',
    text: "",
    faction: 'Being',
    textLeft: "Glasses",
    textRight: "Ribbons",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-1b',
    imgUrl: '/decks/chapter4/beings/white/cape.png',
    title:'Why',
    text: "",
    faction: 'Being',
    textLeft: "Cape",
    textRight: "Hats",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-1c',
    imgUrl: '/decks/chapter4/beings/white/dice.png',
    title:'Why',
    text: "",
    faction: 'Being',
    textLeft: "Dice",
    textRight: "Cherry",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-1d',
    imgUrl: '/decks/chapter4/beings/white/ring.png',
    title:'Why',
    text: "",
    faction: 'Being',
    textLeft: "King",
    textRight: "Ring",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-1e',
    imgUrl: '/decks/chapter4/beings/white/swords.png',
    title:'Why',
    text: "",
    faction: 'Being',
    textLeft: "Sword",
    textRight: "Swords",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
  },

  // Purple (Higher wins)
  {
    id: 'chapter4-being-2a',
    imgUrl: '/decks/chapter4/beings/purple/glasses.png',
    title:'Which',
    text: "",
    faction: 'Being',
    textLeft: "Glasses",
    textRight: "Necklace",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-2b',
    imgUrl: '/decks/chapter4/beings/purple/halo.png',
    title:'Which',
    text: "",
    faction: 'Being',
    textLeft: "Halo",
    textRight: "Necklace",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-2c',
    imgUrl: '/decks/chapter4/beings/purple/pink.png',
    title:'Which',
    text: "",
    faction: 'Being',
    textLeft: "white",
    textRight: "pink",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-2d',
    imgUrl: '/decks/chapter4/beings/purple/strawberry.png',
    title:'Which',
    text: "",
    faction: 'Being',
    textLeft: "strawberry",
    textRight: "ribbon",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-2e',
    imgUrl: '/decks/chapter4/beings/purple/wings.png',
    title:'Which',
    text: "",
    faction: 'Being',
    textLeft: "Tinkle",
    textRight: "Wings",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 0,
    },
  },

  // Blue (Guess who)
  {
    id: 'chapter4-being-3a',
    imgUrl: '/decks/chapter4/beings/blue/alexander.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Felix",
    textRight: "Alexander",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  {
    id: 'chapter4-being-3b',
    imgUrl: '/decks/chapter4/beings/blue/winkle.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Winkle",
    textRight: "Tinkle",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-3c',
    imgUrl: '/decks/chapter4/beings/blue/shelly.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Shelly",
    textRight: "Shelby",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-3d',
    imgUrl: '/decks/chapter4/beings/blue/estelle.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Nidale",
    textRight: "Estelle",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  {
    id: 'chapter4-being-3e',
    imgUrl: '/decks/chapter4/beings/blue/gahndel.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Gahndel",
    textRight: "Geldahn",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-3f',
    imgUrl: '/decks/chapter4/beings/blue/geldahn.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Gahndel",
    textRight: "Geldahn",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: -1,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  {
    id: 'chapter4-being-3g',
    imgUrl: '/decks/chapter4/beings/blue/gallock.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Gale",
    textRight: "Gallock",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  {
    id: 'chapter4-being-3h',
    imgUrl: '/decks/chapter4/beings/blue/hayden.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Hayden",
    textRight: "Moses",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-3i',
    imgUrl: '/decks/chapter4/beings/blue/moses.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Hayden",
    textRight: "Moses",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  {
    id: 'chapter4-being-3j',
    imgUrl: '/decks/chapter4/beings/blue/hugo.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Marco",
    textRight: "Hugo",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  {
    id: 'chapter4-being-3k',
    imgUrl: '/decks/chapter4/beings/blue/luna.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Luna",
    textRight: "Melody",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-3l',
    imgUrl: '/decks/chapter4/beings/blue/oscar.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "August",
    textRight: "Oscar",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  {
    id: 'chapter4-being-3m',
    imgUrl: '/decks/chapter4/beings/blue/powder.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Flower",
    textRight: "Powder",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  {
    id: 'chapter4-being-3n',
    imgUrl: '/decks/chapter4/beings/blue/ruck.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Ruck",
    textRight: "Gruck",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
    actionRight: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
  },
  {
    id: 'chapter4-being-3o',
    imgUrl: '/decks/chapter4/beings/blue/spinkle.png',
    title:'Who',
    text: "",
    faction: 'Being',
    textLeft: "Tinkle",
    textRight: "Spinkle",
    location: 'Choice',
    appearsWithIcon: '',
    actionLeft: {
      heart: 1,
      diamond: -1,
      greenAura: -1,
      yellowAura: 1,
      brain: -1,
      smiley: 1,
      knife: -1,
      cleaver: 1,
      memory: 0,
    },
    actionRight: {
      heart: -1,
      diamond: 1,
      greenAura: 1,
      yellowAura: -1,
      brain: 1,
      smiley: -1,
      knife: 1,
      cleaver: -1,
      memory: 1,
    },
  },
  


]);

export default beings;