import { writable } from 'svelte/store';

const chapter2 = writable([
    // White monk - ALL
    {
        id: 'chapter2-1a',
        imgUrl: '/decks/chapter2/monk-white-1.png',
        title:'Hayden',
        text: 'Everything has a natural rythm, if you listen closely you can hear it.',
        faction: 'Monk',
        textLeft: "I'm listening but I don't hear anything.",
        textRight: "I won't waste my time listening to nothing.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-1b',
        imgUrl: '/decks/chapter2/monk-white-1.png',
        title:'Hayden',
        text: 'Ohhmmmmmmmmmmmmmmmmmmmm...',
        faction: 'Monk',
        textLeft: "OooohhhhMMMmmMMmmMmmmmmm...",
        textRight: "I could never meditate.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 0,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-1c',
        imgUrl: '/decks/chapter2/monk-white-1.png',
        title:'Hayden',
        text: "If you're looking for answers, you must seek within",
        faction: 'Monk',
        textLeft: "When I look within, I see nothing.",
        textRight: "Why don't you focus within yourself instead.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 0,
            auraYellow: 0,
            memory: 1,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-1d',
        imgUrl: '/decks/chapter2/monk-white-2.png',
        title:'Hayden',
        text: "I sense a great disturbance within you.",
        faction: 'Monk',
        textLeft: "Yeah, it started when you started talking to me.",
        textRight: "I will make an effort to be more at peace.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-1e',
        imgUrl: '/decks/chapter2/monk-white-2.png',
        title:'Hayden',
        text: "If you encounter Moses in this forest, he's a fellow student of the monastery and a gentle soul.",
        faction: 'Monk',
        textLeft: "I'll be sure to keep an eye out.",
        textRight: "Actually I have met him, it's like talking to the same person.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Brown monk - ALL
    {
        id: 'chapter2-2a',
        imgUrl: '/decks/chapter2/monk-brown.png',
        title:'Moses',
        text: "Sometimes Hayden can come off as a bit preachy, but he's got a good heart, mind and soul.",
        faction: 'Moses',
        textLeft: "You both seem to be good hearted people, I feel at peace around you.",
        textRight: "He should spend more time focusing on himself.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: 1,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-2b',
        imgUrl: '/decks/chapter2/monk-brown.png',
        title:'Moses',
        text: "You must always be mindful of all living beings, that includes animals and vegetation as well.",
        faction: 'Moses',
        textLeft: "I don't care what happens to plants.",
        textRight: "I don't care what happens to animals.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-2c',
        imgUrl: '/decks/chapter2/monk-brown.png',
        title:'Moses',
        text: "You seem like you've been running when you could have been walking. Maybe it's time to slow down.",
        faction: 'Moses',
        textLeft: "You're right, I haven't had a moment to catch my breath.",
        textRight: "You seem like someone who should mind their own business.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-2d',
        imgUrl: '/decks/chapter2/monk-brown-smile.png',
        title:'Moses',
        text: "I came here to be in touch with nature, but I didn't expect to find magical creatures.",
        faction: 'Moses',
        textLeft: "Life is full of surprises, some good and some bad.",
        textRight: "I'm not sure if I can trust those beasts.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 0,
            auraYellow: 1,
            memory: 1,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-2e',
        imgUrl: '/decks/chapter2/monk-brown-smile.png',
        title:'Moses',
        text: "As much as I sit in thought, I cannot remember if I was always a monk. Where was I before I came to this forest?",
        faction: 'Moses',
        textLeft: "It will come to you when the time is right.",
        textRight: "Instead of sitting, try jogging your memory.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Blue Fairy - ALL
    {
        id: 'chapter2-3a',
        imgUrl: '/decks/chapter2/fairy-blue.png',
        title:'Spinkle',
        text: "Humans confuse me, why do they run when faced with unfamiliar beings?",
        faction: 'Fairy',
        textLeft: "Could be your face?",
        textRight: "Aren't you the least bit frightened to meet a stranger like me?",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 0,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-3b',
        imgUrl: '/decks/chapter2/fairy-blue.png',
        title:'Spinkle',
        text: "I live in this forest with my 2 sisters, but recently there have been a lot of visitors.",
        faction: 'Fairy',
        textLeft: "You should offer to help them get settled.",
        textRight: "I wonder why everyone showed up here around the same time?",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 0,
            auraYellow: 0,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-3c',
        imgUrl: '/decks/chapter2/fairy-blue.png',
        title:'Spinkle',
        text: "Hey there, I'm Spinkle! Please don't confuse me with Winkle, she can be such a handful.",
        faction: 'Fairy',
        textLeft: "No promises.",
        textRight: "A real fairy, wow.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 0,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-3d',
        imgUrl: '/decks/chapter2/fairy-blue.png',
        title:'Spinkle',
        text: "Sometimes I worry about my younger sisters, one tends to get into trouble and the other is too trusting.",
        faction: 'Fairy',
        textLeft: "Getting into trouble is part of life.",
        textRight: "You should keep an eye on them.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-3e',
        imgUrl: '/decks/chapter2/fairy-blue.png',
        title:'Spinkle',
        text: "My sisters and I are magical triplets, born from the same ingredients. Still, they refer to me as their \"big sister\".",
        faction: 'Fairy',
        textLeft: "Maybe you were the first one out the tube.",
        textRight: "Sugar, spice and everything nice?",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: 0,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Purple Fairy - ALL
    {
        id: 'chapter2-4a',
        imgUrl: '/decks/chapter2/fairy-purple.png',
        title:'Tinkle',
        text: "Woah a human, want to be best friends?",
        faction: 'Fairy',
        textLeft: "Not particularly, no.",
        textRight: "Sounds awesome.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 1,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: 0,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-4b',
        imgUrl: '/decks/chapter2/fairy-purple.png',
        title:'Tinkle',
        text: "You have a nice face, I haven't seen many like it.",
        faction: 'Fairy',
        textLeft: "You also have a nice face.",
        textRight: "I also haven't seen a face like yours.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-4c',
        imgUrl: '/decks/chapter2/fairy-purple.png',
        title:'Tinkle',
        text: "Spinkle never trusts anybody, but people are good! I don't understand why she doesn't understand that.",
        faction: 'Fairy',
        textLeft: "You aren't trying to understand her side.",
        textRight: "You should make her understand your side.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-4d',
        imgUrl: '/decks/chapter2/fairy-purple.png',
        title:'Tinkle',
        text: "Spinkle, Winkle and Tinkle, the super duper awesome fairy berry very cherry trio!!!",
        faction: 'Fairy',
        textLeft: "Aren't you a little too excited?",
        textRight: "You on that pixie dust?",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-4e',
        imgUrl: '/decks/chapter2/fairy-purple.png',
        title:'Tinkle',
        text: "Hey I'm Tinkle... wait have we already met?",
        faction: 'Fairy',
        textLeft: "Yes, but we can meet again.",
        textRight: "You all look alike, it's confusing.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Green Fairy - ALL
    {
        id: 'chapter2-4a',
        imgUrl: '/decks/chapter2/fairy-green.png',
        title:'Winkle',
        text: "Winkle here, not winkle, WRINKLE. Wait, no I mean not wrinkle it's winkle, WINKLE!",
        faction: 'Fairy',
        textLeft: "You need to slow down.",
        textRight: "You trying to become a rapper?",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-4b',
        imgUrl: '/decks/chapter2/fairy-green.png',
        title: 'Winkle',
        text: "Humans I meet are surprised that fairies exist, but even more so that we aren't tiny, why would we be tiny?",
        faction: 'Fairy',
        textLeft: "Imagine how I felt when I met Tinkle.",
        textRight: "Stories told us you were small, I guess reading those books were a waste of time.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 0,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-4c',
        imgUrl: '/decks/chapter2/fairy-green.png',
        title:'Winkle',
        text: "You're probably like all the other humans, greedy and rude.",
        faction: 'Fairy',
        textLeft: "You're giving me some strong elf vibes.",
        textRight: "Humans are the worst, you won't hear any arguments here.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 0,
            auraYellow: 0,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-4d',
        imgUrl: '/decks/chapter2/fairy-green.png',
        title:'Winkle',
        text: "I bet you wish you could fly too.",
        faction: 'Fairy',
        textLeft: "I bet you wish you weren't green.",
        textRight: "Flapping my wings all day would surely tire me out.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: -1,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-4e',
        imgUrl: '/decks/chapter2/fairy-green.png',
        title:'Winkle',
        text: "My sisters seem to think we've always lived here... but I don't know. Part of me feels like there was something before all of this.",
        faction: 'Fairy',
        textLeft: "Then try to find a way back.",
        textRight: "Patience, over time they might remember too.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Druid  - ALL
    {
        id: 'chapter2-5a',
        imgUrl: '/decks/chapter2/druid.png',
        title:'Deku',
        text: "Leave this place.",
        faction: 'Druid',
        textLeft: "Such hospitality, I think I'll stay.",
        textRight: "Believe me, I would love to.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-5b',
        imgUrl: '/decks/chapter2/druid.png',
        title:'Deku',
        text: "(ㆆ_ㆆ)",
        faction: 'Druid',
        textLeft: "...",
        textRight: "Staring contest?",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-5c',
        imgUrl: '/decks/chapter2/druid.png',
        title: 'Deku',
        text: "Who are you people?",
        faction: 'Druid',
        textLeft: "I don't even know who I am, don't ask me about the others.",
        textRight: "Woah a talking tree.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-5d',
        imgUrl: '/decks/chapter2/druid.png',
        title:'Deku',
        text: "I guard this forest alone, I don't know what became of the other druids.",
        faction: 'Druid',
        textLeft: "Maybe they got repotted.",
        textRight: "Are you sure the forest even needs to be guarded?",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-5e',
        imgUrl: '/decks/chapter2/druid.png',
        title:'Deku',
        text: "You humans are no friend to nature, therefore I am no friend to humans.",
        faction: 'Druid',
        textLeft: "I'll think about you the next time I eat a salad.",
        textRight: "Not all humans are the same, don't make judgements so quickly.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Rabbit - Yellow AURA, the rabbit is one of the 8 special chars that will be revealed as a victim (this was a rabbit jack killed as a child, represented by Yellow aura for energetic).
    {
        id: 'chapter2-6a',
        imgUrl: '/decks/chapter2/rabbit.png',
        title:'🐰Bounder',
        text: "*Sniff* *Sniff*",
        faction: '🐇Lapin',
        textLeft: "Hey there little hare, come to hang for a bit?",
        textRight: "I wonder if you'd make a better pet or stew.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: 1,
            auraYellow: -1,
            memory: 1, // hang for a bit
        },
        actionRight: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-6b',
        imgUrl: '/decks/chapter2/rabbit.png',
        title:'🐰Bounder',
        text: "*Sniff* *Sniff* *Sniff* *Sniff* *Sniff* *Sniff*!!!",
        faction: '🐇Lapin',
        textLeft: "UNPAW ME YOU WASCALLY WABBIT!",
        textRight: "Slow your hops mr. rabbit, I'm not to be sniffed.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-6c',
        imgUrl: '/decks/chapter2/rabbit.png',
        title:'🐰Bounder',
        text: "*Sniff*...",
        faction: '🐇Lapin',
        textLeft: "That's a nice distance, stay there.",
        textRight: "I should sniff you back so you know how it feels.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-6d',
        imgUrl: '/decks/chapter2/rabbit.png',
        title:'🐰Bounder',
        text: "The rabbit stares at you and smiles. :-3",
        faction: '🐇Lapin',
        textLeft: "Let's just sit here and relax.",
        textRight: "*Walk away*",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-6e',
        imgUrl: '/decks/chapter2/rabbit.png',
        title:'🐰Bounder',
        text: "Yo, watchu sayin' dawg?",
        faction: '🐇Lapin',
        textLeft: "Oh hell no, it's a gangstarabbit!",
        textRight: "Nun much, just chillin'.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Snake - ALL
    {
        id: 'chapter2-7a',
        imgUrl: '/decks/chapter2/snake.png',
        title:'Pentsser',
        text: "What'ss up friend, you want ssome sspecial weaponss?",
        faction: 'Sirpent',
        textLeft: "No thankss, ssoundss like a ssscam!",
        textRight: "I have no need for weapons.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-7b',
        imgUrl: '/decks/chapter2/snake.png',
        title:'Pentsser',
        text: "SSay, you look like a man who needss a new sscimitar!",
        faction: 'Sirpent',
        textLeft: "I think I look more like someone walking away.",
        textRight: "No need, but I'll take a look at your wares.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-7c',
        imgUrl: '/decks/chapter2/snake.png',
        title:'Pentsser',
        text: "SSurfs up on new sshieldss perfect for sshield ssurfing on ssale at Pentsserss only!!!",
        faction: 'Sirpent',
        textLeft: "I wonder if I should take a look...",
        textRight: "You won't tempt me snake!",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-7d',
        imgUrl: '/decks/chapter2/snake.png',
        title:'Pentsser',
        text: "SSir, sstop right there! You musst take a look at my sshop behind thesse busshess...",
        faction: 'Sirpent',
        textLeft: "Sorry but, does anyone fall for that?",
        textRight: "Maybe don't have a shop behind bushes.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 1, // wants to know for himself
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-7e',
        imgUrl: '/decks/chapter2/snake.png',
        title:'Pentsser',
        text: "SSurprissed I can talk? SSo am I, sss-ss-ss-ss-ssss!",
        faction: 'Sirpent',
        textLeft: "Is that you trying to laugh?",
        textRight: "How odd, I wonder why.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 0,
            auraYellow: 1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Hippy-boy - GREEN AURA, Ziggy is one of the 8 special chars that will be revealed as a victim (he and jack grew up together, GREEN aura symbolizes Ziggy's favorite passtime).
    {
        id: 'chapter2-8a',
        imgUrl: '/decks/chapter2/hippy-boy.png',
        title:'Ziggy',
        text: "Maaan you're totally like the first normal lookin dude I've seen here.",
        faction: 'Human',
        textLeft: "Yeah, this forest has a lot of interesting... creatures.",
        textRight: "I'm glad we aren't the only ones wandering around.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 1,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-8b',
        imgUrl: '/decks/chapter2/hippy-boy.png',
        title:'Ziggy',
        text: "You know, before I got here man... I was like, I was. I was totally like... um-",
        faction: 'Human',
        textLeft: "True that.",
        textRight: "Don't worry, many people here are fighting to regain their memories.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-8c',
        imgUrl: '/decks/chapter2/hippy-boy.png',
        title:'Ziggy',
        text: "So like, I'm walking through the forest for some reason ya know... and I'm looking for... shoot my mind's totally blank man.",
        faction: 'Human',
        textLeft: "Didn't happen to find magic mushrooms did you?",
        textRight: "Maybe you should drink some water.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: 1,
            auraYellow: 1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-8d',
        imgUrl: '/decks/chapter2/hippy-boy.png',
        title:'Ziggy',
        text: "Woah... you know something? I think I'm here with a friend, I totally forgot hahaha. Wonder where she is now?",
        faction: 'Human',
        textLeft: "I bet she wonders where you are too.",
        textRight: "It seems you have a special case of this amnesia.",
        actionLeft: {
            heart: 0,
            diamond: 0,
            auraGreen: -1,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: 0,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-8e',
        imgUrl: '/decks/chapter2/hippy-boy.png',
        title:'Ziggy',
        text: "POWDER!!! That's what I forgot, it's powder man! I need to find power!",
        faction: 'Human',
        textLeft: "Glad you remembered, sad you'll forget again.",
        textRight: "I think you should find \"powder\" on your own.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: 0,
            auraYellow: 0,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // Hippy-girl - ALL
    {
        id: 'chapter2-8a',
        imgUrl: '/decks/chapter2/hippy-girl.png',
        title:'Powder',
        text: "Have you seen um... Have you seen... Ahhh forget it.",
        faction: 'Human',
        textLeft: "No, you should try to remember.",
        textRight: "Guess it wasn't important.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-8b',
        imgUrl: '/decks/chapter2/hippy-girl.png',
        title:'Powder',
        text: "Hey, the names Powder. I can't remember what I'm doing in these woods, but I know I'm doing something.",
        faction: 'Human',
        textLeft: "Yeah? Join the club.",
        textRight: "You remind me of someone, stay strong.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: 0,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-8c',
        imgUrl: '/decks/chapter2/hippy-girl.png',
        title:'Powder',
        text: "Zion? Zack..? Z-zzz..... zzzzi- Zigo? Ziga? Ughh forget it.",
        faction: 'Human',
        textLeft: "I want to help, but I kind of also want to watch.",
        textRight: "Take your time, I believe.",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: 1,
            auraYellow: -1,
            memory: 1,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: 1,
            auraYellow: -1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-8d',
        imgUrl: '/decks/chapter2/hippy-girl.png',
        title:'Powder',
        text: "Did I forget again? Whatever, if I am here with someone, they'll find me eventually. I give up on looking.",
        faction: 'Human',
        textLeft: "Take a break, but don't give up.",
        textRight: "Now that's a plan and a half.",
        actionLeft: {
            heart: 1,
            diamond: -1,
            auraGreen: 1,
            auraYellow: -1,
            memory: 1,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            auraGreen: 1,
            auraYellow: -1,
            memory: 0,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },
    {
        id: 'chapter2-8e',
        imgUrl: '/decks/chapter2/hippy-girl.png',
        title:'Powder',
        text: "Oh.My.God. I forgot about Ziggy AGAIN! Ziggyyyyyyyy!!!",
        faction: 'Human',
        textLeft: "It's like watching a dog chase their tail.",
        textRight: "One day you'll find each other, one day...",
        actionLeft: {
            heart: -1,
            diamond: 1,
            auraGreen: -1,
            auraYellow: 1,
            memory: 1,
        },
        actionRight: {
            heart: 1,
            diamond: -1,
            auraGreen: 1,
            auraYellow: -1,
            memory: 1,
        },
        location: 'Choice',
        appearsWithIcon: ''
    },

    // TODO: Add 4 chars, 2 for yellow aura 2 for green aura.
]);

export default chapter2;