import { writable } from 'svelte/store';

const soldiers = writable([
    // Oscar
    {
        id: 'chapter1-s-1a',
        imgUrl: '/decks/chapter1/soldiers/soldier-red.png',
        title:'Oscar',
        text: "I've been fighting for as long as I can remember, but I can't seem to remember anything else.",
        faction: 'Soldier',
        textLeft: "We're in the same boat then soldier, but stay strong.",
        textRight: "A life of violence is a wasted one.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 0,
            diamond: 0,
            memory: 2,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-1b',
        imgUrl: '/decks/chapter1/soldiers/soldier-red.png',
        title:'Oscar',
        text: "Why do I always have to do everything around here! Leave me alone, I'm not in the mood.",
        faction: 'Soldier',
        textLeft: "You need to learn to relax before your face stays like that permanently.",
        textRight: "Yeah it must be really hard to pull your own weight.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-1c',
        imgUrl: '/decks/chapter1/soldiers/soldier-red.png',
        title:'Oscar',
        text: "The other soldiers are a joke, they don't belong in the army.",
        faction: 'Soldier',
        textLeft: "You'd think you'd be the captain then, wouldn't you.",
        textRight: "I'm sure you'd love to go to war alone then.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-1d',
        imgUrl: '/decks/chapter1/soldiers/soldier-red.png',
        title:'Oscar',
        text: "Sleep is for the weak, all those slackers do is waste the day away. Useless sacks of potatoes I tell you.",
        faction: 'Soldier',
        textLeft: "Maybe you should do something about it instead of complaining.",
        textRight: "Your hard work is recognized, thank you for your service.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-1e',
        imgUrl: '/decks/chapter1/soldiers/soldier-red.png',
        title:'Oscar',
        text: "I can't talk right now, I need to go train.",
        faction: 'Soldier',
        textLeft: "Sorry to bother you.",
        textRight: "Yes you probably do.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
    },

    // August
    {
        id: 'chapter1-s-2a',
        imgUrl: '/decks/chapter1/soldiers/soldier-brown.png',
        title:'August',
        text: 'You can never be too careful, always stay on guard and question your surroundings.',
        faction: 'Soldier',
        textLeft: "I do seem to be having a hard time relaxing my guard around here.",
        textRight: "I bet you sleep with one eye open.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 2,
        },
        actionRight: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-2b',
        imgUrl: '/decks/chapter1/soldiers/soldier-brown.png',
        title:'August',
        text: "This peaceful village doesn't need soldiers like us mocking about. Nothing ever seems to happen here, and yet here we all are.",
        faction: 'Soldier',
        textLeft: "You never know what tomorrow holds in store for you.",
        textRight: "Probably better to stay here where it's safe anyway.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 0,
            diamond: 0,
            memory: 2,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-2c',
        imgUrl: '/decks/chapter1/soldiers/soldier-brown.png',
        title:'August',
        text: "This village is a nice place to rest my weary bones, but I don't want to stay forever.",
        faction: 'Soldier',
        textLeft: "It's important to rest, but the key is not to rest for too long.",
        textRight: "Would staying be so bad?",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-2d',
        imgUrl: '/decks/chapter1/soldiers/soldier-brown.png',
        title:'August',
        text: "I never wanted to be a soldier you know, but I was drafted back when I still a child.",
        faction: 'Soldier',
        textLeft: "I'm surprised you managed to stay alive this long.",
        textRight: "You could always fake your death and run away.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-2e',
        imgUrl: '/decks/chapter1/soldiers/soldier-brown.png',
        title:'August',
        text: "If I run away from the army, do you think they'll have me hanged?",
        faction: 'Soldier',
        textLeft: "It's a strong possibility.",
        textRight: "You'll be fine, just don't look back.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
    },

    // Dedu
    {
        id: 'chapter1-s-3a',
        imgUrl: '/decks/chapter1/soldiers/soldier-black.png',
        title:'Dedu',
        text: "I've come a long way from my home village, the people here do not know war like my people do.",
        faction: 'Soldier',
        textLeft: "Don't judge people before getting to know them.",
        textRight: "I'm sorry you have to live through that.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: -2,
            diamond: 2,
            memory: 2,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-3b',
        imgUrl: '/decks/chapter1/soldiers/soldier-black.png',
        title:'Dedu',
        text: "If I could, I think I would return to my village. But, it's simply not in the cards.",
        faction: 'Soldier',
        textLeft: "Perhaps one day.",
        textRight: "I play with my own deck.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: -2,
            diamond: 2,
            memory: 2,
        },
    },
    {
        id: 'chapter1-s-3c',
        imgUrl: '/decks/chapter1/soldiers/soldier-black.png',
        title:'Dedu',
        text: "...",
        faction: 'Soldier',
        textLeft: "He seems to have something on his mind, maybe I should leave him alone.",
        textRight: "...",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-3d',
        imgUrl: '/decks/chapter1/soldiers/soldier-black.png',
        title:'Dedu',
        text: "You know, you actually remind me of someone I've long since forgotten. I wonder who it was?",
        faction: 'Soldier',
        textLeft: "I couldn't tell you.",
        textRight: "Let me know if you remember.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            memory: 2,
        },
    },
    {
        id: 'chapter1-s-3e',
        imgUrl: '/decks/chapter1/soldiers/soldier-black.png',
        title:'Dedu',
        text: "Life isn't all about the glory of battle, but it doesn't hurt to know how to defend yourself.",
        faction: 'Soldier',
        textLeft: "I suppose you're right, but I don't want to hurt anyone.",
        textRight: "If push comes to shove, I can defend myself just fine.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: -2,
            diamond: 2,
            memory: 2,
        },
    },
    

    // Captain Hugo
    {
        id: 'chapter1-s-4a',
        imgUrl: '/decks/chapter1/soldiers/captain.png',
        title:'Hugo',
        text: "The names Hugo, you might've met Dedu, August or Oscar already. Those are my men, they're here to help if you need.",
        faction: 'Soldier',
        textLeft: "They seem to be more interested on taking it easy than helping me.",
        textRight: "Thank you, I appreciate the comforting words.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-4b',
        imgUrl: '/decks/chapter1/soldiers/captain.png',
        title:'Hugo',
        text: "My men aren't the greatest, but they're fine men nonetheless. I would take an arrow for any of them.",
        faction: 'Soldier',
        textLeft: "I wish I could serve under you.",
        textRight: "One can only hope they'd do the same for you.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-4c',
        imgUrl: '/decks/chapter1/soldiers/captain.png',
        title:'Hugo',
        text: "I keep having this dream, one of my men is bleeding out, but I can never reach them in time... what do you think it means?",
        faction: 'Soldier',
        textLeft: 'Maybe you worry too much about the safety of your men?',
        textRight: "Perhaps that's a question only you could answer.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
        actionRight: {
            heart: 0,
            diamond: 0,
            memory: 0,
        },
    },
    {
        id: 'chapter1-s-4d',
        imgUrl: '/decks/chapter1/soldiers/captain.png',
        title:'Hugo',
        text: "I used to overcome my fears on the battlefield, but now it's as if I have no fear at all...",
        faction: 'Soldier',
        textLeft: "You don't need to brag to me, I can already see you're a brave warrior.",
        textRight: "Fear exists in all living beings, perhaps you've just suppressed it.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 2,
        },
    },
    {
        id: 'chapter1-s-4e',
        imgUrl: '/decks/chapter1/soldiers/captain.png',
        title:'Hugo',
        text: "What makes a great leader?",
        faction: 'Soldier',
        textLeft: "Making hard decisions, even if it means abandoning one of your men.",
        textRight: "Listening to your people and allowing everyone to have a say.",
        location: 'Choice',
        appearsWithIcon: '',
        actionLeft: {
            heart: -2,
            diamond: 2,
            memory: 0,
        },
        actionRight: {
            heart: 2,
            diamond: -2,
            memory: 0,
        },
    },
]);

export default soldiers;